# Generated by Django 4.2.24 on 2025-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BridgePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfn', models.CharField(help_text='Structure File Number', max_length=50)),
                ('inspection_id', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='bridge_photos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='bridge_photos/thumbnails/')),
            ],
            options={
                'db_table': 'Bridge_Photos',
            },
        ),
    ]
